# Generated by Django 6.1 on 2026-09-01 14:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stage', models.PositiveSmallIntegerField(choices=[(1, 'Segmentation'), (2, 'Classification'), (3, 'Extraction')])),
                ('prompt_version', models.CharField(max_length=64)),
                ('llm_response_raw', models.JSONField()),
                ('model_name', models.CharField(max_length=128)),
                ('latency_ms', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_entries', to='contracts.clause')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_entries', to='contracts.contract')),
            ],
            options={
                'verbose_name_plural': 'audit log entries',
                'ordering': ['stage', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_type', models.CharField(choices=[('payout_frequency', 'Payout frequency'), ('milestone_trigger', 'Milestone trigger'), ('penalty_amount', 'Penalty amount'), ('notice_period', 'Notice period'), ('auto_renewal_term', 'Auto-renewal term')], max_length=32)),
                ('value_raw', models.TextField()),
                ('value_structured', models.JSONField(default=dict)),
                ('extraction_confidence', models.FloatField()),
                ('needs_human_review', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_terms', to='contracts.clause')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
