# Generated by Django 6.1 on 2026-09-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlogentry',
            name='chain_sequence',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='entry_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
