# Generated by Django 6.1 on 2026-09-01 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_id', models.CharField(max_length=255)),
                ('raw_text', models.TextField()),
                ('source_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_reference_type', models.CharField(choices=[('payout', 'Payout'), ('subscription', 'Subscription')], max_length=32)),
                ('razorpay_reference_id', models.CharField(max_length=255)),
                ('needs_human_review', models.BooleanField(default=False)),
                ('human_review_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_index', models.PositiveIntegerField()),
                ('clause_text', models.TextField()),
                ('clause_type', models.CharField(blank=True, choices=[('payment_schedule', 'Payment schedule'), ('termination', 'Termination'), ('penalty_late_fee', 'Penalty / late fee'), ('dispute_resolution', 'Dispute resolution'), ('auto_renewal', 'Auto-renewal'), ('indemnity', 'Indemnity'), ('other', 'Other'), ('needs_human_review', 'Needs human review')], max_length=32, null=True)),
                ('classification_confidence', models.FloatField(blank=True, null=True)),
                ('classification_rationale', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.contract')),
            ],
            options={
                'ordering': ['sequence_index'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'sequence_index'), name='unique_clause_sequence_per_contract')],
            },
        ),
    ]
