# Generated by Django 6.1 on 2026-09-01 17:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('payout', 'Payout'), ('subscription', 'Subscription'), ('token', 'Token')], max_length=32)),
                ('razorpay_id', models.CharField(max_length=255)),
                ('payload', models.JSONField()),
                ('razorpay_created_at', models.DateTimeField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_records', to='contracts.contract')),
            ],
            options={
                'ordering': ['razorpay_created_at'],
            },
        ),
        migrations.CreateModel(
            name='MismatchFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mismatch_type', models.CharField(choices=[('cadence_mismatch', 'Cadence mismatch'), ('amount_mismatch', 'Amount mismatch'), ('missing_platform_evidence', 'Missing platform evidence'), ('trigger_condition_unverifiable', 'Trigger condition unverifiable')], max_length=32)),
                ('expected_value', models.JSONField()),
                ('actual_value', models.JSONField()),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mismatch_flags', to='pipeline.extractedterm')),
                ('platform_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mismatch_flags', to='razorpay_integration.platformrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
