# Generated by Django 6.1 on 2026-09-01 17:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical'), ('needs_human_review', 'Needs human review')], max_length=32)),
                ('asymmetry_score', models.FloatField(validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('explanation', models.TextField()),
                ('suggested_rewrite', models.TextField(blank=True, null=True)),
                ('linked_mismatch_flag_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clause', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='contracts.clause')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('asymmetry_score__gte', -1), ('asymmetry_score__lte', 1)), name='risk_assessment_asymmetry_score_range')],
            },
        ),
    ]
